services:
  backend:
    container_name: smart-agenda-backend
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - PORT=5001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - smart-agenda-network    

  frontend:
    container_name: smart-agenda-frontend
    build: ./frontend
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - NODE_ENV=development
      - API_URL=http://localhost:5001
    depends_on:
      - backend
    networks:
      - smart-agenda-network  
networks:
  smart-agenda-network:
    driver: bridge